services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  app:
    ports:
      - "8080:8080"
    image: ${APP_IMAGE:-fraud-detection-app:latest}
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      SPRING_PROFILES_ACTIVE: production
      MODEL_SERVICE_URL: http://model:8000
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  model:
    image: ${MODEL_IMAGE:-fraud-model:latest}
    environment:
      MODEL_VERSION: ${MODEL_VERSION:-v1}
      MODEL_DIR: /app/models/${MODEL_VERSION:-v1}
    volumes:
      - model_data:/app/models
    networks: [fraud-detection-network]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: "0.9"
        reservations:
          memory: 512M
          cpus: "0.3"

volumes:
  model_data: