services:
  nginx:
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"

  app:
    image: ${APP_IMAGE:-fraud-detection-app:latest}
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      SPRING_PROFILES_ACTIVE: production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  model:
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: "0.9"
        reservations:
          memory: 512M
          cpus: "0.3"