services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  app:
    image: ${APP_IMAGE:-fraud-detection-app:latest}
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"